# we first do a git pull and clear content to be sure we don't get any merge conflicts

- name: git pull
  become: true
  ansible.builtin.shell:
    chdir: "{{ build_path }}/{{ project }}/{{ content_name }}"
    cmd: git pull

- name: clear articles + pages on build
  become: true
  ansible.builtin.shell: 
    cmd: rm -rf {{ build_path }}/{{ project }}/{{ content_name }}/{{ item }}/*
  loop: "{{ collections }}"

- name: "copy articles and pages from statamic copy to {{ build_path }}/{{ project }}/{{ user }}/{{ content_path }}"
  become: true
  ansible.builtin.shell:
    chdir: "{{ build_path }}/{{ project }}/{{ content_name }}"
    cmd: "cp -r {{ statamic_path }}/content/collections/{{item }} ."
  loop: "{{ collections }}"
