# we first do a git pull and clear content to be sure we don't get any merge conflicts

- name: git pull
  become: true
  ansible.builtin.command:
    chdir: "{{ content_dir }}"
    cmd: git pull

- name: clear articles + pages on build
  become: true
  ansible.builtin.shell:
    cmd: rm -rf {{ content_dir }}/{{ item }}/*
  loop: "{{ content_collections }}"

- name: copy articles and pages from statamic to local git repo
  become: true
  ansible.builtin.command:
    chdir: "{{ content_dir }}"
    cmd: "cp -r {{ php_dir }}/content/collections/{{item }} ."
  loop: "{{ content_collections }}"

- name: stage changes locally  
  ansible.builtin.command:
    cmd: git add *
    chdir: "{{ content_dir }}"

- name: commit changes locally in build dir to local git repo
  ansible.builtin.command:
    cmd: git commit -m "updated content by {{ user }}"
    chdir: "{{ content_dir }}"

- name: push changes to remote repo
  ansible.builtin.command:
    cmd: git push
    chdir: "{{ content_dir }}" 

