- name: git checkout {{ content_repo }} in {{ workdir }}
  become: true
  ansible.builtin.shell:
    chdir: "{{ workdir }}"
    cmd: "git checkout {{ content_branch }}"

- name: git pull
  become: true
  ansible.builtin.shell:
    chdir: "{{ workdir }}"
    cmd: git pull

- name: copy content collections from {{ workdir }} to statamic content collections
  become: true
  ansible.builtin.shell:
    chdir: "{{ workdir }}"
    cmd: "cp -r {{item }} {{ phpdir }}/content/collections/"
  loop: "{{ contentcollections }}"

- name: make statamic content collections rw for user www-data
  become: true
  ansible.builtin.shell:
    cmd: "chown  -R www-data:www-data {{ phpdir }}/content/collections/"

# - name: copy assets to statamic container
#   become: true
#   ansible.builtin.shell:
#     chdir: "{{ build_path }}/{{ project }}/{{ user }}/{{ content_path }}"
#     cmd: "cp -r {{item }} /var/www/{{ project }}_{{ user }}/public/assets"    
#   loop:
#     - trn
#     - calendar

# - name: make statamic assets www-data rw
#   become: true
#   ansible.builtin.shell:
#     cmd: "chown  -R www-data:www-data /var/www/{{ project }}_{{ user }}/public/assets"

- name: clear stache
  become: true
  ansible.builtin.shell:
    chdir: "{{ phpdir }}"
    cmd: "php please stache:clear"

- name: make statamic storage rw for user www-data
  become: true
  ansible.builtin.shell:
    cmd: "chown  -R www-data:www-data {{ phpdir }}/storage"