- name: define collection_dir variables ending on slash
  set_fact:
    collection_dir_st: "{{ php_dir }}/content/collections/"
    collection_dir_repo: "{{ content.srcdir }}/{{ repo.name }}/content"

- name: show collection dir
  debug:
    var: "{{ item }}"
  loop:
    - collection_dir_st
    - collection_dir_repo

- name: git checkout {{ contentrepo.url }} in {{ content.srcdir }}/{{ repo.name }}
  become: true
  ansible.builtin.shell:
    chdir: "{{ content.srcdir }}/{{ repo.name }}"
    cmd: "git checkout {{ repo_branch }} --"

- name: git pull
  become: true
  ansible.builtin.shell:
    chdir: "{{ content.srcdir }}/{{ repo.name }}"
    cmd: git pull

- name: copy content collections from {{ content_dir }} to statamic content collections
  become: true
  ansible.builtin.shell:
    chdir: "{{ content.srcdir }}/{{ repo.name }}"
    cmd: "cp -r content/{{item }} {{ php_dir }}/content/collections/"
  loop: "{{ content.collections }}"

- name: make statamic content collections rw for user www-data
  become: true
  ansible.builtin.shell:
    cmd: "chown  -R www-data:www-data {{ php_dir }}/content/collections/"

- name: clear stache
  become: true
  ansible.builtin.shell:
    chdir: "{{ php_dir }}"
    cmd: "php please stache:clear"

- name: make statamic storage rw for user www-data
  become: true
  ansible.builtin.shell:
    cmd: "chown  -R www-data:www-data {{ php_dir }}/storage"