- name: git checkout {{ content_repo }} in {{ build_path }}/{{ project }}
  become: true
  ansible.builtin.shell:
    chdir: "{{ build_path }}/{{ project }}/{{ content_name }}"
    cmd: "git checkout {{ content_branch }}"

- name: git pull
  become: true
  ansible.builtin.shell:
    chdir: "{{ build_path }}/{{ project }}/{{ content_name }}"
    cmd: git pull

- name: copy collections from {{ build_path }}/{{ project }}/{{ user }}/{{ content_path }} to statamic 
  become: true
  ansible.builtin.shell:
    chdir: "{{ build_path }}/{{ project }}/{{ content_name }}"
    cmd: "cp -r {{item }} {{ statamic_path }}/content/collections/"
  loop: "{{ collections }}"

- name: make statamic collections www-data rw
  become: true
  ansible.builtin.shell:
    cmd: "chown  -R www-data:www-data {{ statamic_path }}/content/collections/"

# - name: copy assets to statamic container
#   become: true
#   ansible.builtin.shell:
#     chdir: "{{ build_path }}/{{ project }}/{{ user }}/{{ content_path }}"
#     cmd: "cp -r {{item }} /var/www/{{ project }}_{{ user }}/public/assets"    
#   loop:
#     - trn
#     - calendar

# - name: make statamic assets www-data rw
#   become: true
#   ansible.builtin.shell:
#     cmd: "chown  -R www-data:www-data /var/www/{{ project }}_{{ user }}/public/assets"

- name: clear stache
  become: true
  ansible.builtin.shell:
    chdir: "{{ statamic_path }}"
    cmd: "php please stache:clear"
