- name: git checkout {{ content_repo }} in {{ content_dir }}
  become: true
  ansible.builtin.shell:
    chdir: "{{ content_dir }}"
    cmd: "git checkout {{ content_branch }}"

- name: git pull
  become: true
  ansible.builtin.shell:
    chdir: "{{ content_dir }}"
    cmd: git pull

- name: copy content collections from {{ content_dir }} to statamic content collections
  become: true
  ansible.builtin.shell:
    chdir: "{{ content_dir }}"
    cmd: "cp -r {{item }} {{ php_dir }}/content/collections/"
  loop: "{{ content_collections }}"

- name: make statamic content collections rw for user www-data
  become: true
  ansible.builtin.shell:
    cmd: "chown  -R www-data:www-data {{ php_dir }}/content/collections/"

- name: clear stache
  become: true
  ansible.builtin.shell:
    chdir: "{{ php_dir }}"
    cmd: "php please stache:clear"

- name: make statamic storage rw for user www-data
  become: true
  ansible.builtin.shell:
    cmd: "chown  -R www-data:www-data {{ php_dir }}/storage"