- name: create /root/.ssh
  ansible.builtin.file:
    path: /root/.ssh
    state: directory

- name: configure ssh to disable host check for github
  ansible.builtin.copy:
    src: ssh_github.conf
    dest: /etc/ssh/ssh_config.d/github.conf

# setup ssh keys for github

- name: set id_rsa variables
  ansible.builtin.set_fact:
    id_rsa: "{{ lookup('ansible.builtin.env', 'ID_RSA', default='') }}"
    id_rsa_pub: "{{ lookup('ansible.builtin.env', 'ID_RSA_PUB', default='') }}"

- name: set id_rsa private key
  ansible.builtin.copy:
    content: "{{ id_rsa }}"
    dest: /root/.ssh/id_rsa
    mode: 0600
  when: id_rsa

- name: set id_rsa public key
  ansible.builtin.copy:
    content: "{{ id_rsa_pub }}"
    dest: /root/.ssh/id_rsa_pub
    mode: 0644
  when: id_rsa

- name: configure git user.name and user email
  ansible.builtin.shell:
    cmd: git cconfig  --global  {{ item }}
  loop:
    - "user.name {{ repo.gitusername }}"    
    - "user.email {{ repo.gitemail }}"    

# setup content directory

- name: clear the content repo dir
  ansible.builtin.file:
    state: "{{ item }}"
    path: "{{ content.srcdir }}"
  loop:
    - absent 
    - directory

- name: clone the content repo to 
  ansible.builtin.shell:
    chdir: "{{ content.srcdir }}"
    cmd: git clone {{ repo.url }}

# configure php statamic

- name: create statamic .env file
  ansible.builtin.copy:
    dest: "{{ php_dir }}/.env"
    src: statamic_env

- name: make statamic belonging to user www-data
  ansible.builtin.file:
    path: "{{ php_dir }}"
    state: directory
    owner: www-data
    group: www-data
    recurse: yes

# configure python gunicorn

- name: configure gunicorn
  ansible.builtin.copy:
    src: gunicorn.conf.py
    dest: /app/python/

# configure nginx

- name: set nginxport variable
  ansible.builtin.set_fact:
    nginxport: "{{ lookup('ansible.builtin.env', 'PORT', default='8080') }}"


- name: Configure nginx
  ansible.builtin.template:
    src: "{{ 'nginx.conf.https.j2' if use_https else 'nginx.conf.http.j2' }}"
    dest: /etc/nginx/nginx.conf