- name: create .git directory is it is not existing
  ansible.builtin.file:
    state: directory
    path: "{{ workdir }}/.git"

- name: configure ssh to disable host check for github
  ansible.builtin.copy:
    src: ssh_github.conf
    dest: /etc/ssh/ssh_config.d/github.conf

- name: configure gunicorn
  ansible.builtin.copy:
    src: gunicorn.conf.py
    dest: /app/python/

- name: configure git to inject GIT_TOKEN in the url
  ansible.builtin.template:
    src: git_config
    dest: "{{ workdir }}/.git/config"

- name: clear stache on statamic
  ansible.builtin.shell:
    chdir: /app/kbsbmgr
    cmd: php please stache:clear