content_repo: git@github.com:cropr/kbsbcontent.git
content_name: kbsbcontent
content_dir: /app/content/kbsbcontent
content_collections:
  - articles
  - pages
frontend_repo: git@github.com:cropr/kbsb.git
php_dir: /app/php/kbsbmgr
