---
- hosts: localhost
  gather_facts: no

  tasks:

    - name: load services variables
      include_vars:
        file: "vars/{{ project }}.yml"

    - name: copy statamic to build
      vars:
        workdir: "{{ build_path }}/{{ content_name }}"
        phpdir:  "/app/{{ project }}"    
      include_role:
        name: checkout_content

    - name: deploy production
      vars:
        workdir: "{{ build_path }}/{{ content_name }}"
        phpdir:  "/app/{{ project }}"    
      include_role:
        name: deploy_production 
      
