---
- hosts: localhost
  gather_facts: no

  tasks:

    - name: load services variables
      include_vars:
        file: "vars/{{ project }}.yml"

    - name: copy statamic to build
      include_role:
        name: copy_statamic2build

    - name: launch preview
      include_role:
        name: launch_preview  
      
